#!/bin/bash

apt-get -y install fish direnv exa
chsh -s /usr/bin/fish

# Bat isn't on this
wget https://github.com/sharkdp/bat/releases/download/v0.18.2/bat_0.18.2_amd64.deb
dpkg -i bat_0.18.2_amd64.deb

# copy over config
rm -rf ~/.config
cp -r /workspaces/.codespaces/.persistedshare/dotfiles/.config ~/.config
mkdir ~/.config/vscode-dev-containers
touch ~/.config/vscode-dev-containers/first-run-notice-already-displayed
